-- Migration: Create payment_transactions table
-- Bảng lưu lịch sử giao dịch VNPay

CREATE TABLE IF NOT EXISTS public.payment_transactions (
    id bigint NOT NULL,
    invoice_id bigint NOT NULL,
    transaction_ref character varying(100) NOT NULL UNIQUE,
    amount double precision NOT NULL,
    status character varying(50) NOT NULL,
    vnp_transaction_no character varying(100),
    bank_code character varying(20),
    response_code character varying(10),
    order_info character varying(500),
    created_at timestamp(6) without time zone NOT NULL,
    paid_at timestamp(6) without time zone,
    secure_hash character varying(500),
    CONSTRAINT payment_transactions_pkey PRIMARY KEY (id),
    CONSTRAINT payment_transactions_status_check CHECK (((status)::text = ANY ((ARRAY['PENDING'::character varying, 'SUCCESS'::character varying, 'FAILED'::character varying, 'CANCELLED'::character varying])::text[])))
);

-- Tạo sequence cho ID
ALTER TABLE public.payment_transactions ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.payment_transactions_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);

-- Foreign key
ALTER TABLE ONLY public.payment_transactions
    ADD CONSTRAINT fk_payment_transaction_invoice FOREIGN KEY (invoice_id) REFERENCES public.invoices(id);

-- Indexes
CREATE INDEX idx_payment_transactions_invoice_id ON public.payment_transactions(invoice_id);
CREATE INDEX idx_payment_transactions_transaction_ref ON public.payment_transactions(transaction_ref);
CREATE INDEX idx_payment_transactions_status ON public.payment_transactions(status);
CREATE INDEX idx_payment_transactions_created_at ON public.payment_transactions(created_at DESC);

COMMENT ON TABLE public.payment_transactions IS 'Lịch sử giao dịch thanh toán qua VNPay';
COMMENT ON COLUMN public.payment_transactions.transaction_ref IS 'Mã giao dịch unique (vnp_TxnRef)';
COMMENT ON COLUMN public.payment_transactions.vnp_transaction_no IS 'Mã GD từ VNPay (vnp_TransactionNo)';
COMMENT ON COLUMN public.payment_transactions.response_code IS 'Mã phản hồi từ VNPay (00=success)';
COMMENT ON COLUMN public.payment_transactions.secure_hash IS 'Hash từ VNPay để verify';
