-- Migration: Create invoices table
-- Tạo bảng invoices để lưu hóa đơn khi user vượt base usage

CREATE TABLE IF NOT EXISTS public.invoices (
    id bigint NOT NULL,
    subscription_id bigint NOT NULL,
    swap_transaction_id bigint NOT NULL,
    amount double precision NOT NULL,
    status character varying(50) NOT NULL,
    usage_type character varying(50) NOT NULL,
    overage double precision NOT NULL,
    rate double precision NOT NULL,
    description character varying(500),
    created_at timestamp(6) without time zone NOT NULL,
    paid_at timestamp(6) without time zone,
    CONSTRAINT invoices_pkey PRIMARY KEY (id),
    CONSTRAINT invoices_status_check CHECK (((status)::text = ANY ((ARRAY['PENDING'::character varying, 'PAID'::character varying, 'CANCELLED'::character varying])::text[]))),
    CONSTRAINT invoices_usage_type_check CHECK (((usage_type)::text = ANY ((ARRAY['DISTANCE'::character varying, 'ENERGY'::character varying])::text[])))
);

-- Tạo sequence cho ID
ALTER TABLE public.invoices ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.invoices_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);

-- Foreign keys
ALTER TABLE ONLY public.invoices
    ADD CONSTRAINT fk_invoice_subscription FOREIGN KEY (subscription_id) REFERENCES public.subscriptions(id);

ALTER TABLE ONLY public.invoices
    ADD CONSTRAINT fk_invoice_swap_transaction FOREIGN KEY (swap_transaction_id) REFERENCES public.swap_transactions(id);

-- Indexes để tối ưu query
CREATE INDEX idx_invoices_subscription_id ON public.invoices(subscription_id);
CREATE INDEX idx_invoices_status ON public.invoices(status);
CREATE INDEX idx_invoices_swap_transaction_id ON public.invoices(swap_transaction_id);
CREATE INDEX idx_invoices_created_at ON public.invoices(created_at DESC);

-- Unique constraint: 1 swap transaction chỉ tạo 1 invoice
ALTER TABLE ONLY public.invoices
    ADD CONSTRAINT uk_invoice_swap_transaction UNIQUE (swap_transaction_id);

COMMENT ON TABLE public.invoices IS 'Hóa đơn phát sinh khi user vượt base usage (baseMileage hoặc baseEnergy)';
COMMENT ON COLUMN public.invoices.amount IS 'Số tiền phải trả (VND)';
COMMENT ON COLUMN public.invoices.overage IS 'Số lượng vượt (km hoặc kWh)';
COMMENT ON COLUMN public.invoices.rate IS 'Đơn giá tier rate (VND/km hoặc VND/kWh)';
COMMENT ON COLUMN public.invoices.description IS 'Mô tả chi tiết: Overage: X km/kWh × Y₫/unit = Z₫';
